# Utilisez l'image de base officielle PHP 7.4 avec Apache
FROM php:7.4-apache

# Copiez le contenu du dossier src (où se trouve votre script PHP) dans le dossier /var/www/html du conteneur
COPY src/ /var/www/html/

# Exposez le port 80 pour permettre l'accès au serveur web depuis l'extérieur du conteneur
EXPOSE 80
