apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactapp
        image: tchessi/reactapp:latest  # Mis à jour le chemin de l'image
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: reactapp-service
spec:
  type: NodePort
  selector:
    app: reactapp
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32000
