apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-back-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mern-back
  template:
    metadata:
      labels:
        app: mern-back
    spec:
      containers:
      - name: mern-back
        image: tchessi/mern-back:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: mern-back-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30020  # Spécifiez ce port ou laissez-le vide pour une attribution automatique
  selector:
    app: mern-back
